# Netlify configuration file
# For more details see https://www.netlify.com/docs/netlify-toml-reference/

[build]
  publish = "build/docs/html5"
  command = "./config/travis/download_gradle_wrapper.sh && ./gradlew -b build.gradle.txt asciidoctor"
